#!/bin/bash

if [ $1 == "install" -o $1 == "upgrade" ]; then

	/etc/init.d/lirc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ -f /etc/lirc/lircd.conf ]; then
		mv --backup=t /etc/lirc/lircd.conf /etc/lirc/lircd.conf.xbian
	fi

	if [ -f /etc/lirc/hardware.conf ]; then
		mv --backup=t /etc/lirc/hardware.conf /etc/lirc/hardware.conf.xbian
	fi

	if [ -f /etc/lirc/lircmd.conf ]; then
		mv --backup=t /etc/lirc/lircmd.conf /etc/lirc/lircmd.conf.xbian
	fi

	if [ ! -d "/etc/default" ]; then
		mkdir -p "/etc/default";
	fi

	if [ ! -d "/etc/init.d" ]; then
		mkdir -p "/etc/init.d";
	fi

	if [ ! -d "/etc/lirc" ]; then
		mkdir -p "/etc/lirc";
	fi

	if [ ! -d "/etc/lirc/hardware" ]; then
		mkdir -p "/etc/lirc/hardware";
	fi

	if [ ! -d "/etc/lirc/remotes" ]; then
		mkdir -p "/etc/lirc/remotes";
	fi

	if [ ! -d "/lib/udev/rules.d" ]; then
		mkdir -p "/lib/udev/rules.d";
	fi

	if [ ! -d "/usr/local/lib" ]; then
		mkdir -p "/usr/local/lib";
	fi

	if [ ! -d "/usr/lib/iguanaIR" ]; then
		mkdir -p "/usr/lib/iguanaIR";
	fi

	if [ ! -d "/usr/lib" ]; then
		mkdir -p "/usr/lib";
	fi

	if [ ! -d "/usr/local/include/lirc" ]; then
		mkdir -p "/usr/local/include/lirc";
	fi

	if [ ! -d "/usr/include" ]; then
		mkdir -p "/usr/include";
	fi

	if [ ! -d "/usr/local/sbin" ]; then
		mkdir -p "/usr/local/sbin";
	fi

	if [ ! -d "/usr/bin" ]; then
		mkdir -p "/usr/bin";
	fi

	if [ ! -d "/usr/local/bin" ]; then
		mkdir -p "/usr/local/bin";
	fi

fi
