#!/bin/bash

if [ $1 == "remove" ]; then

	/etc/init.d/lirc stop 1>/dev/null 2>/dev/null >/dev/null

	if [ -f /usr/local/bin/ircat ]; then
		rm /usr/local/bin/ircat;
	fi
	
	if [ -f /usr/local/bin/irexec ]; then
		rm /usr/local/bin/irexec;
	fi
	
	if [ -f /usr/local/bin/irpty ]; then
		rm /usr/local/bin/irpty;
	fi
	
	if [ -f /usr/local/bin/irrecord ]; then
		rm /usr/local/bin/irrecord;
	fi
	
	if [ -f /usr/local/bin/irsend ]; then
		rm /usr/local/bin/irsend;
	fi
	
	if [ -f /usr/local/bin/irw ]; then
		rm /usr/local/bin/irw;
	fi
	
	if [ -f /usr/local/bin/mode2 ]; then
		rm /usr/local/bin/mode2;
	fi
	
	if [ -f /usr/local/bin/pronto2lirc ]; then
		rm /usr/local/bin/pronto2lirc;
	fi
	
	if [ -d /usr/local/include/lirc ]; then
		rm -r /usr/local/include/lirc;
	fi
	
	if [ -f /usr/local/lib/liblirc_client.so.0 ]; then
		rm /usr/local/lib/liblirc_client.so.0;
	fi
	
	if [ -f /usr/local/lib/liblirc_client.so ]; then
		rm /usr/local/lib/liblirc_client.so;
	fi
	
	if [ -f /usr/local/lib/liblirc_client.so.0.2.1 ]; then
		rm /usr/local/lib/liblirc_client.so.0.2.1;
	fi
		
	if [ -f /usr/local/lib/liblirc_client.a ]; then
		rm /usr/local/lib/liblirc_client.a;
	fi
	
	if [ -f /usr/local/lib/liblirc_client.la ]; then
		rm /usr/local/lib/liblirc_client.la;
	fi
	
	if [ -d /usr/local/sbin/lircd ]; then
		rm -r /usr/local/sbin/lircd;
	fi
	
	if [ -d /usr/local/sbin/lircmd ]; then
		rm -r /usr/local/sbin/lircmd;
	fi
	
	if [ -d /etc/init.d/lirc ]; then
		rm -r /etc/init.d/lirc;
	fi
	
	if [ -d /etc/lirc/lircd.conf ]; then
		rm -r /etc/lirc/lircd.conf;
	fi
	
	if [ -d /etc/lirc/lircmd.conf ]; then
		rm -r /etc/lirc/lircmd.conf;
	fi
	
	if [ -d /etc/lirc/hardware.conf ]; then
		rm -r /etc/lirc/hardware.conf;
	fi

	if [ -f /etc/default/iguanaIR ]; then
		rm  /etc/default/iguanaIR;
	fi

	if [ -f /etc/init.d/iguanaIR ]; then
		rm /etc/init.d/iguanaIR;
	fi

	if [ -f /lib/udev/rules.d/80-iguanaIR.rules ]; then
		rm /lib/udev/rules.d/80-iguanaIR.rules;
	fi

	if [ -f /usr/lib/iguanaIR/libusb.so ]; then
		rm /usr/lib/iguanaIR/libusb.so;
	fi

	if [ -f /usr/lib/libiguanaIR.so ]; then
		rm /usr/lib/libiguanaIR.so;
	fi

	if [ -f /usr/include/iguanaIR.h ]; then
		rm /usr/include/iguanaIR.h;
	fi

	if [ -f /usr/bin/igclient ]; then
		rm /usr/bin/igclient;
	fi

	if [ -f /usr/bin/igdaemon ]; then
		rm /usr/bin/igdaemon;
	fi

fi

if [ $1 == "upgrade" ]; then
	
	if [ -f /usr/local/lib/liblirc_client.so.0 ]; then
		rm /usr/local/lib/liblirc_client.so.0;
	fi
	
	if [ -f /usr/local/lib/liblirc_client.so ]; then
		rm /usr/local/lib/liblirc_client.so;
	fi	
	
fi
